# Generated by Django 4.2.18 on 2025-01-28 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_remove_booking_yoga_class_booking_class_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'class_schedule', 'booking_date')},
        ),
    ]
